### ISSUE TITLE
Databricks module doesn't let users create clusters

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-resource-modules#18]
@simon-wang-gc the co-ops were not able to create clusters - is this expected? Could we let them create clusters and only restrict the types of clusters?

**Comment by simon-wang-gc** [comment]
Currently we do not have policy setup in project specific databricks, so I will grant them admin. However, we do need to bring the cluster policy constructs to the project modules.

**Comment by simon-wang-gc** [comment]
Created issue #411 to track the implementation of cluster policies. So I am closing this issue.
